name: flutter_buoi11
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  font_awesome_flutter: ^10.7.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # setup sử dụng font bên ngoài
  fonts:
    - family: Playwrite # đặt tên font
      fonts:
        - asset: assets/fonts/playwrite.ttf # đường dẫn trỏ tới file font
    - family: stencil
      fonts:
        - asset: assets/fonts/stencil.ttf

  # setup sử dụng thư mục hình ảnh
  assets:
    - assets/imgs/
